### ISSUE TITLE
Refine documentation

### ISSUE THREAD

**Issue by koppor** [uklance/gradle-java-flavours#1]
I am trying to use this plugin. However, I get following output with Gradle 3.5:

    Plugin with id 'com.lazan.javaflavours' not found.

Is it because of a missing release?

Is it possible to say a few words on the integration with the [shadow plugin](https://github.com/johnrengelman/shadow)? I'd like to have a fat JAR. Maybe I just have to patch the task dependencies somehow. #

**Comment by uklance** [comment]
The plugin portal gives you two code snippets for adding plugins to your build. Please use one of the snippets from [here](https://plugins.gradle.org/plugin/com.lazan.javaflavours)
